config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :episodes
  resource :subscription
  resource :card

  root to: 'episodes#index'


end

app/models/episode.rb
class Episode < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def subscribed?
    stripe_subscription_id?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user_subscribed?
    user_signed_in? && current_user.subscribed?
  end
  helper_method :current_user_subscribed?
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user_subscribed?

  def update
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    subscription = customer.subscriptions.retrieve(current_user.stripe_subscription_id)
    subscription.source = params[:stripeToken]
    subscription.save

    current_user.update(
      card_last4: params[:card_last4],
      card_exp_month: params[:card_exp_month],
      card_exp_year: params[:card_exp_year],
      card_type: params[:card_brand]
    )

    redirect_to edit_user_registration_path, notice: "Successfully updated your card!"
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all.order("created_at DESC")
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :redirect_to_signup, only: [:new]
  def show

  end

  def new
  end

  def create
      customer = if current_user.stripe_id?
                  Stripe::Customer.retrieve(current_user.stripe_id)
                else
                  Stripe::Customer.create(email: current_user.email)
                end

    subscription = customer.subscriptions.create(
        source: params[:stripeToken],
        plan: "athens_silver"
    )
    options = {
      stripe_id: customer.id,
      stripe_subscription_id: subscription.id,
    }

    options.merge!(
      card_last4: params[:card_last4],
      card_exp_month: params[:card_exp_month],
      card_exp_year: params[:card_exp_year],
      card_type: params[:card_brand]
    ) if params[:card_last4]

    current_user.update(options)

    redirect_to root_path, notice: "You've been subscribed!"
  end

  def destroy
    customer = Stripe::Customer.retrieve(current_user.stripe_id)
    customer.subscriptions.retrieve(current_user.stripe_subscription_id).delete
    current_user.update(stripe_subscription_id: nil)

    redirect_to root_path, notice: "Your subscription has been canceled. Thank you!"
  end

  private

    def redirect_to_signup
      if !user_signed_in?
        session["user_return_to"] = new_subscription_path
        redirect_to new_user_registration_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def card_fields_class
    "hidden" if current_user.card_last4?
  end

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-danger", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
          concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
            concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
            concat content_tag(:span, 'Close', class: 'sr-only')
          end)
        concat message
      end)
    end
    nil
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing Episodes</h1>

<% @episodes.each do |episode| %>
  <h2><%= link_to episode.title, episode %></h2>
<% end %>
<hr />
<%= link_to 'New Episode', new_episode_path, class: 'btn btn-primary' %>

app/views/episodes/new.html.erb
<h1>New Episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<h1><%= @episode.title %></h1>

<p>
  <strong>Description:</strong>
  <%= @episode.description %>
</p>

<% if current_user_subscribed? %>
  Haiahaha secret to only subscrbed!
<% else %>
  <%= link_to "Subscribe to watch", new_subscription_path, class: "btn btn-primary" %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "StripeTest", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-support fa-fw"></i> Screencasts <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to episodes_path do %>
                  <i class="fa fa-list fa-fw"></i> All Episodes
                <% end %>
              </li>
              <li>
                <%= link_to new_episode_path do %>
                  <i class="fa fa-plus-square-o fa-fw"></i>  New Episode
                <% end %>
              </li>
            </ul>
          </li>
      </ul>
    <% end %>
      <!--<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search account">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-fw"></i> <%= current_user.email %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to edit_user_registration_path do %>
                    <i class="fa fa-cog fa-fw"></i> Manage Account
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                      <i class="fa fa-sign-out fa-fw"></i>   Sign Out
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in fa-fw"></i> Sign In
            <% end %>
          </li>
          <li>
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user-plus fa-fw"></i> Sign Up
              <% end %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StripeTest</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'https://js.stripe.com/v2/', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

  <%= tag :meta, name: "stripe-key", content: Rails.application.secrets.stripe_public %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="container-fluid">
    <%= flash_messages %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/subscriptions/new.html.erb
<h1>Subscribe!</h1>

<%= form_tag subscription_path, id: "payment-form" do %>
  <% if current_user.card_last4? %>
    <div class="card-on-file">
      <p>Your current card on file</p>
      <div><%= current_user.card_type %> **** **** **** <%= current_user.card_last4 %></div>
      <div>Expires <%= current_user.card_exp_month %> / <%= current_user.card_exp_year %></div>
      <p><%= link_to "Use a different card", "#", class: "use-diffent-card" %></p>
    </div>
  <% end %>
<div class="col-md-3">
  <div class="card-fields <%= card_fields_class %>">
    <p class="payment-errors text-center text-danger"></p>

    <div class="form-group">
          <label>
            <span>Card Number</span>
          </label>
            <input value="4242 4242 4242 4242" type="text" size="20" data-stripe="number" class="form-control"/>

    </div>

    <div class="row">
      <div class="col-sm-3">
        <div class="form-group">
          <label>Expiration </label>
          <input value="12" type="text" size="2" placeholder="MM" data-stripe="exp-month" class="form-control"/>
        </div>
      </div>

      <div class="col-sm-3">
        <div class="form-group">
          <label>&nbsp;</label>
          <input value="2020" type="text" size="4" placeholder="YYYY" data-stripe="exp-year" class="form-control"/>
        </div>
      </div>

      <div class="col-sm-3 col-sm-offset-3">
        <div class="form-group">
          <label>
            <span>CVC</span>
          </label>

          <input value="123" type="text" size="4" data-stripe="cvc" class="form-control"/>
        </div>
      </div>
    </div><!-- End row -->

  </div> <!-- End CC form col -->

  <button type="submit" class="btn btn-success btn-md" data-disable-with="<i class='fa fa-spinner fa-spin'></i> Submitting...">Submit Payment</button>

<% end %>
</div><!-- ./col-md-6 -->